// function PaisesMundo(indice) {
let i = 0;
const MisPaises = [
  //! Lista Nacionalidad
  {key: i++, section: true, label: 'Países'},
  {key: i++, label: 'Afghanistan'},
  {key: i++, label: 'Albania'},
  {key: i++, label: 'Algeria'},
  {key: i++, label: 'American'},
  {key: i++, label: 'Samoa'},
  {key: i++, label: 'Andorra'},
  {key: i++, label: 'Angola'},
  {key: i++, label: 'Anguilla'},
  {key: i++, label: 'Antigua and Barbuda'},
  {key: i++, label: 'Argentina'},
  {key: i++, label: 'Armenia'},
  {key: i++, label: 'Aruba'},
  {key: i++, label: 'Australia'},
  {key: i++, label: 'Austria'},
  {key: i++, label: 'Azerbaijan'},
  {key: i++, label: 'Bahamas'},
  {key: i++, label: 'Bahrain'},
  {key: i++, label: 'Bangladesh'},
  {key: i++, label: 'Barbados'},
  {key: i++, label: 'Belarus'},
  {key: i++, label: 'Belgium'},
  {key: i++, label: 'Belize'},
  {key: i++, label: 'Benin'},
  {key: i++, label: 'Bermuda'},
  {key: i++, label: 'Bhutan'},
  {key: i++, label: 'Bolivia'},
  {key: i++, label: 'Bosnia and Herzegovina'},
  {key: i++, label: 'Botswana'},
  {key: i++, label: 'Brazil'},
  {key: i++, label: 'British Virgin IslandsBrunei'},
  {key: i++, label: 'Darussalam'},
  {key: i++, label: 'Bulgaria'},
  {key: i++, label: 'Burkina Faso'},
  {key: i++, label: 'Burundi'},
  {key: i++, label: 'Cabo Verde'},
  {key: i++, label: 'Cambodia'},
  {key: i++, label: 'Cameroon'},
  {key: i++, label: 'Canada'},
  {key: i++, label: 'Canary Islands (Spain)'},
  {key: i++, label: 'Cayman Islands'},
  {key: i++, label: 'Central African Republic'},
  {key: i++, label: 'Chad'},
  {key: i++, label: 'Chile'},
  {key: i++, label: 'China'},
  {key: i++, label: 'Colombia'},
  {key: i++, label: 'Comoros'},
  {key: i++, label: 'Congo, Dem Rep of the'},
  {key: i++, label: 'Congo, Rep of the'},
  {key: i++, label: 'Cook Islands'},
  {key: i++, label: 'Costa Rica'},
  {key: i++, label: 'Côte d´Ivoire'},
  {key: i++, label: 'Croatia'},
  {key: i++, label: 'Cuba'},
  {key: i++, label: 'Cyprus'},
  {key: i++, label: 'Czech Republic'},
  {key: i++, label: 'Denmark'},
  {key: i++, label: 'Djibouti'},
  {key: i++, label: 'Dominica'},
  {key: i++, label: 'Dominican Republic'},
  {key: i++, label: 'Ecuador'},
  {key: i++, label: 'Egypt'},
  {key: i++, label: 'El Salvador'},
  {key: i++, label: 'Equatorial Guinea'},
  {key: i++, label: 'Eritrea'},
  {key: i++, label: 'Estonia'},
  {key: i++, label: 'Eswatini'},
  {key: i++, label: 'Ethiopia'},
  {key: i++, label: 'Fiji'},
  {key: i++, label: 'Finland'},
  {key: i++, label: 'France'},
  {key: i++, label: 'French Guiana'},
  {key: i++, label: 'French Polynesia'},
  {key: i++, label: 'Gabon'},
  {key: i++, label: 'Gambia'},
  {key: i++, label: 'Georgia'},
  {key: i++, label: 'Germany'},
  {key: i++, label: 'Ghana'},
  {key: i++, label: 'Gibraltar (UK)'},
  {key: i++, label: 'Greece'},
  {key: i++, label: 'Greenland'},
  {key: i++, label: 'Grenada'},
  {key: i++, label: 'Guadeloupe'},
  {key: i++, label: 'Guam'},
  {key: i++, label: 'Guatemala'},
  {key: i++, label: 'Guinea'},
  {key: i++, label: 'Guinea-Bissau'},
  {key: i++, label: 'Guyana'},
  {key: i++, label: 'Haiti'},
  {key: i++, label: 'Holy See'},
  {key: i++, label: 'Honduras'},
  {key: i++, label: 'Hong Kong (China)'},
  {key: i++, label: 'Hungary'},
  {key: i++, label: 'Iceland'},
  {key: i++, label: 'India'},
  {key: i++, label: 'Indonesia'},
  {key: i++, label: 'Iran, Islamic Rep of'},
  {key: i++, label: 'Iraq'},
  {key: i++, label: 'Ireland'},
  {key: i++, label: 'Israel'},
  {key: i++, label: 'Italy'},
  {key: i++, label: 'Jamaica'},
  {key: i++, label: 'Japan'},
  {key: i++, label: 'Jordan'},
  {key: i++, label: 'Kaza'},
  {key: i++, label: 'khstan'},
  {key: i++, label: 'Kenya'},
  {key: i++, label: 'Kiribati'},
  {key: i++, label: 'Korea, Dem People´s Rep of'},
  {key: i++, label: 'Korea, Rep ofKuwait'},
  {key: i++, label: 'Kyrgyzstan'},
  {key: i++, label: 'Lao People´s Democratic Republic'},
  {key: i++, label: 'Latvia'},
  {key: i++, label: 'Lebanon'},
  {key: i++, label: 'Lesotho'},
  {key: i++, label: 'Liberia'},
  {key: i++, label: 'Libya'},
  {key: i++, label: 'Liechtenstein'},
  {key: i++, label: 'Lithuania'},
  {key: i++, label: 'Luxembourg'},
  {key: i++, label: 'Macao (China)'},
  {key: i++, label: 'Madagascar'},
  {key: i++, label: 'Malawi'},
  {key: i++, label: 'Malaysia'},
  {key: i++, label: 'Maldives'},
  {key: i++, label: 'Mali'},
  {key: i++, label: 'Malta'},
  {key: i++, label: 'Marshall Islands'},
  {key: i++, label: 'Martinique'},
  {key: i++, label: 'Mauritania'},
  {key: i++, label: 'Mauritius'},
  {key: i++, label: 'Mayotte'},
  {key: i++, label: 'Mexico'},
  {key: i++, label: 'Micronesia, Fed States of'},
  {key: i++, label: 'Moldova'},
  {key: i++, label: 'Monaco'},
  {key: i++, label: 'Mongolia'},
  {key: i++, label: 'Montenegro'},
  {key: i++, label: 'Montserrat'},
  {key: i++, label: 'Morocco'},
  {key: i++, label: 'Mozambique'},
  {key: i++, label: 'Myanmar'},
  {key: i++, label: 'Namibia'},
  {key: i++, label: 'Nauru'},
  {key: i++, label: 'Nepal'},
  {key: i++, label: 'Netherlands Antilles'},
  {key: i++, label: 'Netherlands, the'},
  {key: i++, label: 'New Caledonia'},
  {key: i++, label: 'New Zealand'},
  {key: i++, label: 'Nicaragua'},
  {key: i++, label: 'Niger'},
  {key: i++, label: 'Nigeria'},
  {key: i++, label: 'Niue'},
  {key: i++, label: 'Norfolk Island'},
  {key: i++, label: 'North Macedonia'},
  {key: i++, label: 'Northern Mariana Islands'},
  {key: i++, label: 'Norway'},
  {key: i++, label: 'Oman'},
  {key: i++, label: 'Pakistan'},
  {key: i++, label: 'Palau'},
  {key: i++, label: 'Palestine, State of'},
  {key: i++, label: 'Panama'},
  {key: i++, label: 'Papua New Guinea'},
  {key: i++, label: 'Paraguay'},
  {key: i++, label: 'Peru'},
  {key: i++, label: 'Philippines'},
  {key: i++, label: 'Poland'},
  {key: i++, label: 'Portugal'},
  {key: i++, label: 'Puerto Rico'},
  {key: i++, label: 'Qatar'},
  {key: i++, label: 'Reunion'},
  {key: i++, label: 'Romania'},
  {key: i++, label: 'Russian Federation'},
  {key: i++, label: 'Rwanda'},
  {key: i++, label: 'Saint Barthélemy'},
  {key: i++, label: 'Saint Kitts and Nevis'},
  {key: i++, label: 'Saint Lucia'},
  {key: i++, label: 'Saint Pierre and Miquelon'},
  {key: i++, label: 'Saint Vincent and the Grenadines'},
  {key: i++, label: 'Samoa'},
  {key: i++, label: 'San Marino'},
  {key: i++, label: 'Sao Tome and Principe'},
  {key: i++, label: 'Saudi Arabia'},
  {key: i++, label: 'Senegal'},
  {key: i++, label: 'Serbia'},
  {key: i++, label: 'Seychelles'},
  {key: i++, label: 'Sierra Leone'},
  {key: i++, label: 'Singapore'},
  {key: i++, label: 'Slovakia'},
  {key: i++, label: 'Slovenia'},
  {key: i++, label: 'Solomon Islands'},
  {key: i++, label: 'Somalia'},
  {key: i++, label: 'South Africa'},
  {key: i++, label: 'South Sudan'},
  {key: i++, label: 'Spain'},
  {key: i++, label: 'Sri Lanka'},
  {key: i++, label: 'Sudan'},
  {key: i++, label: 'Suriname'},
  {key: i++, label: 'Sweden'},
  {key: i++, label: 'Switzerland'},
  {key: i++, label: 'Syrian Arab Republic'},
  {key: i++, label: 'Taiwan (China)'},
  {key: i++, label: 'Tajikistan'},
  {key: i++, label: 'Tanzania, United Rep of'},
  {key: i++, label: 'Thailand'},
  {key: i++, label: 'Timor-Leste'},
  {key: i++, label: 'Togo'},
  {key: i++, label: 'Tokelau'},
  {key: i++, label: 'Tonga'},
  {key: i++, label: 'Trinidad and Tobago'},
  {key: i++, label: 'Tunisia'},
  {key: i++, label: 'Turkey'},
  {key: i++, label: 'Turkmenistan'},
  {key: i++, label: 'Turks and Caicos Islands'},
  {key: i++, label: 'Tuvalu'},
  {key: i++, label: 'Uganda'},
  {key: i++, label: 'Ukraine'},
  {key: i++, label: 'United Arab Emirates'},
  {key: i++, label: 'United Kingdom'},
  {key: i++, label: 'United States of America'},
  {key: i++, label: 'United States Virgin Islands'},
  {key: i++, label: 'Uruguay'},
  {key: i++, label: 'Uzbekistan'},
  {key: i++, label: 'Vanuatu'},
  {key: i++, label: 'Venezuela'},
  {key: i++, label: 'Viet Nam'},
  {key: i++, label: 'Wallis and Futuna Islands'},
  {key: i++, label: 'Yemen'},
  {key: i++, label: 'Zambia'},
  {key: i++, label: 'Zimbabwe'},
];
// }

export default MisPaises;
